---
title: "IPL Analysis"
author: "Group"
date: "November 10, 2018"
output: html_document
---
```{r}
library(ggplot2)
library(magrittr)
library(dplyr)
```

```{r}
setwd("F:/Third_year_Materials/Sem5/DataAnalytics_Files/Class_Project/DA_Project-ipl")
deliveries <- read.csv("deliveries.csv")
matches <- read.csv("matches.csv")
deliveries$wickets <- as.numeric(ifelse(deliveries$player_dismissed =="" ,"",1))
```

```{r}
teams <-  deliveries %>% select(batting_team) %>% distinct()

teams <- rename(teams, team = batting_team)  

s_team <- c("SRH","RCB","MI","RPS","GL","KKR","KXIP","DD","CSK","RR","DD","KTK","PWI","RPS")
teams <- cbind(teams, s_team)

player_of_match <- matches%>% select(id,player_of_match,season) %>%
  distinct()

player_of_match <- rename(player_of_match, player=player_of_match)

Season <- data.frame(season=c(2008,2009,2010,2011,2012,2013,2014,2015,2016),T_winner=c("Rajasthan Royals","Deccan Chargers","Chennai Super Kings","Chennai Super Kings","Kolkata Knight Riders","Mumbai Indians","Kolkata Knight Riders","Mumbai Indians","Sunrisers Hyderabad"))


matches$city <- as.character(matches$city)
matches$city[matches$city==""] <- "Dubai"
venue_city <- matches %>%
            select(city)%>%
  distinct()

#geocodes <- geocode(as.character(venue_city$city))
#venue_city <- data.frame(venue_city[,1],geocodes)

#venue_city <-rename(venue_city,city=venue_city...1.)
```

```{r}
dismissal <- deliveries%>%
  left_join(matches, by=c("match_id"="id"))%>%
   left_join(teams,by=c("batting_team"="team"))%>%
  filter(dismissal_kind!="")%>%
  group_by(season,dismissal_kind,s_team)%>%
  summarize(wickets =n())
  
 
 
ggplot(dismissal,aes(x=dismissal_kind,y=wickets,colour=as.factor(season),fill=as.factor(season)))+
  geom_bar(position = "stack", show.legend = TRUE, width =.6,stat="identity")+
      theme(legend.position="bottom")+
     coord_flip()+
  theme(legend.direction = "horizontal")+
  scale_y_continuous(name="wickets")+
    scale_x_discrete(name="dismissal kind")+
                     ggtitle("Breakdown of dismissal type")
```

```{r}
batting_TW <- deliveries%>%
  left_join(matches, by=c("match_id"="id"))%>%
  semi_join(Season, by=c("season"="season","batting_team"="T_winner"))%>%
  left_join(teams,by=c("batting_team"="team"))%>%
                  group_by(season,batting_team,s_team)%>%
      summarize(runs =sum(total_runs))
```

```{r}
bastmen<- deliveries%>%
  left_join(matches, by=c("match_id"="id"))%>%
        group_by(season,batsman)%>%
 summarize(runs =max(sum(batsman_runs,na.rm=TRUE)))%>%
  arrange(season,desc(runs))%>%
  filter(runs==max(runs))

ggplot(bastmen,aes(x=season,y=runs,colour=batsman,fill=batsman))+
  geom_bar(position = "stack",  show.legend = FALSE, width = .6,stat="identity")+
    geom_text(aes(label=batsman,hjust=-.25, colour="green"))+
  theme(legend.position="none")+
     coord_flip()+
  scale_x_discrete(name="Season", limits=c(2008,2009,2010,2011,2012,2013,2014,2015,2016))+
  ggtitle("Highest run scorers by season")
```

```{r}
ggplot(batting_TW,aes(x=season,y=runs,colour=batting_team,fill=batting_team))+
  geom_bar(position = "stack",  show.legend = FALSE, width = .6,stat="identity")+
  geom_text(aes(label=s_team,hjust=-.25, colour="green"))+
  theme(legend.position="none")+
     coord_flip()+
  scale_x_discrete(name="Season", limits=c(2008,2009,2010,2011,2012,2013,2014,2015,2016))+
  ggtitle("Total Runs by Tournament winners by season")
```
```{r}
bowler<- deliveries%>%
  left_join(matches, by=c("match_id"="id"))%>%
  filter(dismissal_kind!="run out")%>%
        group_by(season,bowler)%>%
 summarize(wicket =max(sum(wickets,na.rm=TRUE)))%>%
  arrange(season,desc(wicket))%>%
  filter(wicket==max(wicket))

ggplot(bowler,aes(x=season,y=wicket,colour=bowler,fill=bowler))+
  geom_bar(position = "stack",  show.legend = FALSE, width = .6,stat="identity")+
    geom_text(aes(label=bowler,hjust=-.25, colour="green"))+
  theme(legend.position="none")+
     coord_flip()+
  scale_x_discrete(name="Season", limits=c(2008,2009,2010,2011,2012,2013,2014,2015,2016))+
  ggtitle("Highest wickter takers by season")
```
```{r}
toss <- matches%>%
  left_join(teams,by=c("toss_winner"="team") )%>%
  select(s_team,toss_winner)%>%
   group_by(s_team)%>%
      summarize(wins=n())

toss$type <- "toss"
 
wins <-matches%>%
  left_join(teams,by=c("winner"="team") )%>%
  select(s_team,winner)%>%
   group_by(s_team)%>%
      summarize(wins=n())

wins$type <- "wins"

toss_w <- rbind(toss,wins)

toss_w <- toss_w %>%
  group_by(s_team, type)%>%
summarize(wins=sum(wins))


ggplot(toss_w,aes(x=s_team,y=wins,colour=type,fill=type))+
  geom_bar(position = "dodge",stat = "identity")+
        theme(legend.position="right")+
       scale_y_continuous(name="Toss and Match Wins")+
  scale_x_discrete(name="Toss and Match winner")+
  ggtitle("Toss and Match wins by each Team")
```

```{r}
ggplot(as.data.frame(table(matches$team2) + table(matches$team1)),aes(reorder(Var1,-Freq),Freq,fill = Var1)) +geom_bar(stat = "identity")+
  theme(axis.text.x = element_text(angle = 90, hjust = 1))+ xlab("Team")+
  ylab("Number of Matches") +guides(fill=FALSE)
```